version: "3.8"

services:
  mongo1:
    image: cgr.dev/chainguard/mongodb
    container_name: mongo1
    environment:
      MONGO_INITDB_REPLICA_SET_NAME: "rs0"
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    ports:
      - "27017:27017"
    networks:
      - mongo-replica-set
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo1-data:/data/db

  mongo2:
    image: cgr.dev/chainguard/mongodb
    container_name: mongo2
    environment:
      MONGO_INITDB_REPLICA_SET_NAME: "rs0"
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    ports:
      - "27018:27017"
    networks:
      - mongo-replica-set
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo2-data:/data/db

  mongo3:
    image: cgr.dev/chainguard/mongodb
    container_name: mongo3
    environment:
      MONGO_INITDB_REPLICA_SET_NAME: "rs0"
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    ports:
      - "27019:27017"
    networks:
      - mongo-replica-set
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo3-data:/data/db

networks:
  mongo-replica-set:
    driver: bridge

volumes:
  mongo1-data:
    driver: local
  mongo2-data:
    driver: local
  mongo3-data:
    driver: local
